import { NextResponse } from 'next/server'

const MOCK_TEMPLATES = {
  storyTemplates: [
    {
      id: 't1',
      name: '穿越逆袭模板',
      category: '穿越',
      description: '标准穿越剧开场公式：穿越→困境→金手指→逆袭',
      scriptTemplate: '【开场】主角穿越到异世界，面对生存危机...\n【金手指】获得特殊能力/知识...\n【发展】建立势力，积累资源...\n【高潮】身份揭露，打脸全场...\n【结局】功成名就，抱得美人/成就霸业',
      emoji: '🏰',
      estimatedDuration: '3-5分钟 × 10集',
      tags: ['穿越', '逆袭', '爽文'],
      popularity: 98,
    },
    {
      id: 't2',
      name: '豪门恩怨模板',
      category: '现代言情',
      description: '豪门总裁剧套路：身世之谜→误会→虐恋→真相大白',
      scriptTemplate: '【开局】灰姑娘意外进入豪门...\n【冲突】婆媳/家族内斗...\n【误会】相爱的人因误会分离...\n【真相】身世之谜揭开...\n【结局】破镜重圆 or 遗憾告别',
      emoji: '🏰',
      estimatedDuration: '3-5分钟 × 15集',
      tags: ['豪门', '虐恋', '总裁'],
      popularity: 95,
    },
    {
      id: 't3',
      name: '重生复仇模板',
      category: '重生',
      description: '重生复仇爽文公式：遗憾开场→重生→预知未来→复仇',
      scriptTemplate: '【前世】主角抱憾而死...\n【重生】回到过去，带着前世记忆...\n【布局】利用未来知识步步为营...\n【复仇】一一清算仇人...\n【升华】收获爱情/友情/事业',
      emoji: '🔄',
      estimatedDuration: '3-5分钟 × 12集',
      tags: ['重生', '复仇', '爽文'],
      popularity: 97,
    },
    {
      id: 't4',
      name: '甜宠日常模板',
      category: '甜宠',
      description: '甜宠剧套路：欢喜冤家→日久生情→撒糖不断',
      scriptTemplate: '【相遇】欢喜冤家初见...\n【相处】从互相嫌弃到互相离不开...\n【危机】外部压力/前任/误会...\n【表白】甜蜜告白名场面...\n【日常】婚后/交往后继续撒糖',
      emoji: '💕',
      estimatedDuration: '3-5分钟 × 20集',
      tags: ['甜宠', '爱情', '日常'],
      popularity: 93,
    },
    {
      id: 't5',
      name: '神豪系统模板',
      category: '都市神豪',
      description: '神豪文套路：穷屌丝→获得系统→无限资源→打脸逆袭',
      scriptTemplate: '【开局】被嘲讽的穷小子...\n【转折】获得神豪系统...\n【装逼】用金钱和能力打脸...\n【升级】商业帝国崛起...\n【结局】功成名就，众人拜服',
      emoji: '💳',
      estimatedDuration: '3-5分钟 × 10集',
      tags: ['神豪', '系统', '爽文'],
      popularity: 91,
    },
    {
      id: 't6',
      name: '恐怖悬疑模板',
      category: '恐怖',
      description: '恐怖短剧公式：日常→诡异→恐惧→真相',
      scriptTemplate: '【日常】平静的生活...\n【诡异】奇怪的事情开始发生...\n【恐惧】主角陷入恐怖境地...\n【真相】揭开恐怖背后的秘密...\n【反转】意想不到的结局',
      emoji: '👻',
      estimatedDuration: '2-4分钟 × 8集',
      tags: ['恐怖', '悬疑', '惊悚'],
      popularity: 88,
    },
  ],
  stylePresets: [
    {
      id: 'sp1',
      name: '仙侠古风',
      artStyle: 'fantasy_concept',
      aspectRatio: '9:16',
      castEthnicity: 'east_asian',
      language: '中文',
      mood: '史诗/神秘',
      palette: ['#6c5ce7', '#a855f7', '#ffd700', '#1a1a2e'],
    },
    {
      id: 'sp2',
      name: '都市写实',
      artStyle: 'modern_realism',
      aspectRatio: '9:16',
      castEthnicity: 'east_asian',
      language: '中文',
      mood: '真实/共鸣',
      palette: ['#0984e3', '#00b894', '#f5f5f5', '#2d3436'],
    },
    {
      id: 'sp3',
      name: '赛博朋克',
      artStyle: 'cyberpunk_neon',
      aspectRatio: '16:9',
      castEthnicity: 'mixed',
      language: '多语言',
      mood: '未来/冷酷',
      palette: ['#00f5ff', '#ff00ff', '#6c5ce7', '#0a0a0f'],
    },
    {
      id: 'sp4',
      name: '水墨古风',
      artStyle: 'ink_wash',
      aspectRatio: '16:9',
      castEthnicity: 'east_asian',
      language: '中文',
      mood: '意境/古典',
      palette: ['#2d3436', '#636e72', '#dfe6e9', '#b2bec3'],
    },
  ],
}

export async function GET() {
  return NextResponse.json(MOCK_TEMPLATES)
}
